api_platform:
    title: API Platform
    version: 1.0.0
    show_webby: false
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
